"""initial schema (post tenant-scoping fix)

Revision ID: 40aa6983cc54
Revises: 
Create Date: 2026-07-11 20:22:38.923702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40aa6983cc54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_index',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ref_year', sa.Integer(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_reference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('escalation_index_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_data_tier', sa.Enum('FIRST_PARTY', 'VENDOR', 'PUBLIC', name='datatier'), nullable=False),
    sa.ForeignKeyConstraint(['escalation_index_key'], ['escalation_index.key'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', name='uq_category_path')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_path'), ['path'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'ESTIMATOR', 'APPROVER', 'ADMIN', name='role'), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_email_per_tenant')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_time', ['tenant_id', 'created_at'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('data_tier', sa.Enum('FIRST_PARTY', 'VENDOR', 'PUBLIC', name='datatier'), nullable=False),
    sa.Column('escalation_index_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['escalation_index_key'], ['escalation_index.key'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category_id', 'canonical_name', name='uq_item_tenant_cat_name')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_category_id'), ['category_id'], unique=False)
        batch_op.create_index('ix_item_tenant_cat', ['tenant_id', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operators', sa.JSON(), nullable=True),
    sa.Column('year_range', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', name='uq_benchmark_item')
    )
    with op.batch_alter_table('benchmark', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('item_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalised_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_alias', schema=None) as batch_op:
        batch_op.create_index('ix_alias_tenant_norm', ['tenant_id', 'normalised_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_alias_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_alias_normalised_text'), ['normalised_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_alias_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('TENDER', 'PO', 'INVOICE', 'QUOTE', 'AFE', 'MANUAL', name='sourcetype'), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orig_rate', sa.Float(), nullable=False),
    sa.Column('orig_year', sa.Integer(), nullable=False),
    sa.Column('orig_date', sa.Date(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('spec_snapshot', sa.JSON(), nullable=True),
    sa.Column('normalised_base', sa.Float(), nullable=True),
    sa.Column('norm_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_flag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='obsstatus'), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index('ix_obs_item_status', ['item_id', 'status'], unique=False)
        batch_op.create_index('ix_obs_tenant', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('procurement_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('awarded_price', sa.Float(), nullable=True),
    sa.Column('final_actual_cost', sa.Float(), nullable=True),
    sa.Column('schedule_delay_pct', sa.Float(), nullable=True),
    sa.Column('cost_overrun_pct', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_outcome', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_outcome_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_outcome', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_outcome_tenant_id'))

    op.drop_table('procurement_outcome')
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_observation_status'))
        batch_op.drop_index(batch_op.f('ix_observation_item_id'))
        batch_op.drop_index('ix_obs_tenant')
        batch_op.drop_index('ix_obs_item_status')

    op.drop_table('observation')
    with op.batch_alter_table('item_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_alias_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_item_alias_normalised_text'))
        batch_op.drop_index(batch_op.f('ix_item_alias_item_id'))
        batch_op.drop_index('ix_alias_tenant_norm')

    op.drop_table('item_alias')
    with op.batch_alter_table('benchmark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_benchmark_item_id'))

    op.drop_table('benchmark')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tenant_id'))
        batch_op.drop_index('ix_item_tenant_cat')
        batch_op.drop_index(batch_op.f('ix_item_category_id'))
        batch_op.drop_index(batch_op.f('ix_item_canonical_name'))

    op.drop_table('item')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_time')
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_path'))

    op.drop_table('category')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))
        batch_op.drop_index(batch_op.f('ix_tenant_name'))

    op.drop_table('tenant')
    op.drop_table('escalation_index')
    # ### end Alembic commands ###
