"""drop redundant single-column indexes covered by compound indexes

Revision ID: b331609948d8
Revises: cb451b34cc89
Create Date: 2026-07-15 21:28:13.328553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b331609948d8'
down_revision: Union[str, Sequence[str], None] = 'cb451b34cc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obs_tenant'))
        batch_op.drop_index(batch_op.f('ix_observation_item_id'))
        batch_op.drop_index(batch_op.f('ix_observation_status'))
        batch_op.drop_index(batch_op.f('ix_observation_tenant_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obs_tenant'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
