"""add compound index on observation(tenant_id, status)

Revision ID: cb451b34cc89
Revises: 40aa6983cc54
Create Date: 2026-07-15 21:26:43.310844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb451b34cc89'
down_revision: Union[str, Sequence[str], None] = '40aa6983cc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.create_index('ix_obs_tenant_status', ['tenant_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_tenant_status')

    # ### end Alembic commands ###
